BEGIN;

CREATE TABLE IF NOT EXISTS public.challenge_rooms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  challenge_id BIGINT REFERENCES public.challenges(id) ON DELETE CASCADE NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (id, challenge_id)
);

INSERT INTO public.challenge_rooms (challenge_id)
SELECT id
FROM public.challenges
ON CONFLICT (challenge_id) DO NOTHING;

CREATE OR REPLACE FUNCTION public.create_challenge_room()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.challenge_rooms (challenge_id)
  VALUES (NEW.id)
  ON CONFLICT (challenge_id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

DROP TRIGGER IF EXISTS create_room_for_challenge ON public.challenges;
CREATE TRIGGER create_room_for_challenge
  AFTER INSERT ON public.challenges
  FOR EACH ROW EXECUTE FUNCTION public.create_challenge_room();

ALTER TABLE public.challenge_room_messages
  ADD COLUMN IF NOT EXISTS room_id BIGINT;

UPDATE public.challenge_room_messages AS message
SET room_id = room.id
FROM public.challenge_rooms AS room
WHERE room.challenge_id = message.challenge_id
  AND message.room_id IS DISTINCT FROM room.id;

CREATE UNIQUE INDEX IF NOT EXISTS challenge_rooms_id_challenge_id_key
  ON public.challenge_rooms(id, challenge_id);

CREATE UNIQUE INDEX IF NOT EXISTS challenge_room_messages_id_challenge_room_key
  ON public.challenge_room_messages(id, challenge_id, room_id);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'challenge_room_messages_room_challenge_fkey'
      AND conrelid = 'public.challenge_room_messages'::regclass
  ) THEN
    ALTER TABLE public.challenge_room_messages
      ADD CONSTRAINT challenge_room_messages_room_challenge_fkey
      FOREIGN KEY (room_id, challenge_id)
      REFERENCES public.challenge_rooms(id, challenge_id)
      ON DELETE CASCADE;
  END IF;
END $$;

ALTER TABLE public.challenge_room_messages
  ALTER COLUMN room_id SET NOT NULL;

ALTER TABLE public.challenge_room_message_likes
  ADD COLUMN IF NOT EXISTS room_id BIGINT;

UPDATE public.challenge_room_message_likes AS message_like
SET room_id = room.room_id
FROM public.challenge_room_messages AS room
WHERE room.id = message_like.message_id
  AND room.challenge_id = message_like.challenge_id
  AND message_like.room_id IS DISTINCT FROM room.room_id;

ALTER TABLE public.challenge_room_message_likes
  DROP CONSTRAINT IF EXISTS message_like_room_reference;
ALTER TABLE public.challenge_room_message_likes
  ADD CONSTRAINT message_like_room_reference
  FOREIGN KEY (message_id, challenge_id, room_id)
  REFERENCES public.challenge_room_messages(id, challenge_id, room_id)
  ON DELETE CASCADE;

ALTER TABLE public.challenge_room_message_likes
  ALTER COLUMN room_id SET NOT NULL;

ALTER TABLE public.challenge_rooms ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.challenge_rooms TO authenticated;

DROP POLICY IF EXISTS "Participants can view their challenge rooms"
  ON public.challenge_rooms;
CREATE POLICY "Participants can view their challenge rooms"
  ON public.challenge_rooms FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.user_challenges
      WHERE user_challenges.challenge_id = challenge_rooms.challenge_id
        AND user_challenges.user_id = auth.uid()
    )
    OR EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.is_admin = TRUE
    )
  );

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime'
  ) AND NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'challenge_rooms'
  ) THEN
    ALTER PUBLICATION supabase_realtime
      ADD TABLE public.challenge_rooms;
  END IF;
END $$;

COMMIT;
