-- Shared announcements with per-user read receipts.
-- Run once in the Supabase SQL Editor.

BEGIN;

CREATE TABLE IF NOT EXISTS public.announcements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL CHECK (length(trim(title)) > 0),
  body TEXT NOT NULL CHECK (length(trim(body)) > 0),
  created_by UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  published_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.announcement_reads (
  announcement_id BIGINT NOT NULL
    REFERENCES public.announcements(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  read_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (announcement_id, user_id)
);

ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.announcement_reads ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS announcements_read_published
  ON public.announcements;
CREATE POLICY announcements_read_published
  ON public.announcements
  FOR SELECT
  TO authenticated
  USING (published_at IS NOT NULL);

DROP POLICY IF EXISTS announcements_admin_insert
  ON public.announcements;
CREATE POLICY announcements_admin_insert
  ON public.announcements
  FOR INSERT
  TO authenticated
  WITH CHECK (
    created_by = auth.uid()
    AND EXISTS (
      SELECT 1
      FROM public.profiles
      WHERE profiles.id = auth.uid()
        AND profiles.is_admin = TRUE
    )
  );

DROP POLICY IF EXISTS announcements_admin_update
  ON public.announcements;
CREATE POLICY announcements_admin_update
  ON public.announcements
  FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.profiles
      WHERE profiles.id = auth.uid()
        AND profiles.is_admin = TRUE
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.profiles
      WHERE profiles.id = auth.uid()
        AND profiles.is_admin = TRUE
    )
  );

DROP POLICY IF EXISTS announcements_admin_delete
  ON public.announcements;
CREATE POLICY announcements_admin_delete
  ON public.announcements
  FOR DELETE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.profiles
      WHERE profiles.id = auth.uid()
        AND profiles.is_admin = TRUE
    )
  );

DROP POLICY IF EXISTS announcement_reads_select_own
  ON public.announcement_reads;
CREATE POLICY announcement_reads_select_own
  ON public.announcement_reads
  FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS announcement_reads_insert_own
  ON public.announcement_reads;
CREATE POLICY announcement_reads_insert_own
  ON public.announcement_reads
  FOR INSERT
  TO authenticated
  WITH CHECK (
    user_id = auth.uid()
    AND EXISTS (
      SELECT 1
      FROM public.announcements
      WHERE announcements.id = announcement_id
        AND announcements.published_at IS NOT NULL
    )
  );

GRANT SELECT, INSERT, UPDATE, DELETE
  ON public.announcements TO authenticated;
GRANT USAGE, SELECT
  ON SEQUENCE public.announcements_id_seq TO authenticated;
GRANT SELECT, INSERT
  ON public.announcement_reads TO authenticated;

COMMIT;
