-- ====================================================================
-- FULLSTÄNDIGT DATABASSCHEMA FÖR UTMANINGSAPPEN (SÄKER VERSION)
-- ====================================================================

-- 1. TABELL: profiles (Användarprofiler kopplade till Supabase Auth)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  alias TEXT UNIQUE,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Lägg till en admin-kolumn i profiles-tabellen
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS is_admin BOOLEAN DEFAULT FALSE;

-- 2. TABELL: challenges (Alla aktiva utmaningar skapade av Admin)
CREATE TABLE IF NOT EXISTS public.challenges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  points INT DEFAULT 100 NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Lägg till is_active i challenges-tabellen, förinställt på FALSE
ALTER TABLE public.challenges 
ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT FALSE;

-- Lägg till start- och slutdatum i challenges-tabellen
ALTER TABLE public.challenges 
ADD COLUMN IF NOT EXISTS start_date TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS end_date TIMESTAMPTZ;

-- 3. TABELL: user_challenges (Kopplingstabell: Vem har klarat vad?)
CREATE TABLE IF NOT EXISTS public.user_challenges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  challenge_id BIGINT REFERENCES public.challenges(id) ON DELETE CASCADE NOT NULL,
  completed_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Spärr så att en användare bara kan klara en specifik challenge en gång
  CONSTRAINT unique_user_challenge UNIQUE (user_id, challenge_id)
);

-- Lägg till valbara nivåer i utmaningstabellen
ALTER TABLE public.challenges 
ADD COLUMN IF NOT EXISTS tiers TEXT[] DEFAULT '{}';

-- Lägg till vilken nivå användaren har valt i kopplingstabellen
ALTER TABLE public.user_challenges 
ADD COLUMN IF NOT EXISTS chosen_tier TEXT;

-- ====================================================================
-- SÄKERHETSINSTÄLLNINGAR (Row Level Security - RLS)
-- ====================================================================
ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.challenges DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_challenges DISABLE ROW LEVEL SECURITY;

-- ====================================================================
-- AUTOMATISK PROFILSKAPANDE (Trigger & Funktion)
-- ====================================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, alias)
  VALUES (
    new.id, 
    new.raw_user_meta_data->>'full_name', 
    new.raw_user_meta_data->>'alias'
  )
  ON CONFLICT (id) DO NOTHING; -- Säkrar om profilen redan skulle finnas
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Ta bort gammal trigger om den finns, för att undvika dubbletter innan vi skapar den på nytt
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ====================================================================
-- INITIAL TESTDATA (Läggs bara till om tabellen är helt tom)
-- ====================================================================
INSERT INTO public.challenges (title, description, points)
SELECT 'Första steget', 'Skapa ett konto och logga in i portalen.', 50
WHERE NOT EXISTS (SELECT 1 FROM public.challenges WHERE title = 'Första steget');

INSERT INTO public.challenges (title, description, points)
SELECT 'Kodmaraton', 'Sitt och koda oavbrutet i 60 minuter.', 150
WHERE NOT EXISTS (SELECT 1 FROM public.challenges WHERE title = 'Kodmaraton');

INSERT INTO public.challenges (title, description, points)
SELECT 'Problemlösaren', 'Lös ett komplext problem eller en bugg helt själv.', 200
WHERE NOT EXISTS (SELECT 1 FROM public.challenges WHERE title = 'Problemlösaren');
