-- ====================================================================
-- FULLSTÄNDIGT DATABASSCHEMA FÖR UTMANINGSAPPEN (SÄKER VERSION)
-- ====================================================================

-- 1. TABELL: profiles (Användarprofiler kopplade till Supabase Auth)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email TEXT,
  full_name TEXT,
  alias TEXT UNIQUE,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS email TEXT;

UPDATE public.profiles AS profiles
SET email = users.email
FROM auth.users AS users
WHERE profiles.id = users.id
  AND profiles.email IS NULL;

-- Lägg till en admin-kolumn i profiles-tabellen
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS is_admin BOOLEAN DEFAULT FALSE;

-- 2. TABELL: challenges (Alla aktiva utmaningar skapade av Admin)
CREATE TABLE IF NOT EXISTS public.challenges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  points INT DEFAULT 100 NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Lägg till is_active i challenges-tabellen, förinställt på FALSE
ALTER TABLE public.challenges 
ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT FALSE;

-- Lägg till start- och slutdatum i challenges-tabellen
ALTER TABLE public.challenges 
ADD COLUMN IF NOT EXISTS start_date TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS end_date TIMESTAMPTZ;

-- 3. TABELL: user_challenges (Kopplingstabell: Vem har klarat vad?)
CREATE TABLE IF NOT EXISTS public.user_challenges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  challenge_id BIGINT REFERENCES public.challenges(id) ON DELETE CASCADE NOT NULL,
  completed_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Spärr så att en användare bara kan klara en specifik challenge en gång
  CONSTRAINT unique_user_challenge UNIQUE (user_id, challenge_id)
);

-- Lägg till valbara nivåer i utmaningstabellen
ALTER TABLE public.challenges 
ADD COLUMN IF NOT EXISTS tiers TEXT[] DEFAULT '{}';

-- Lägg till vilken nivå användaren har valt i kopplingstabellen
ALTER TABLE public.user_challenges 
ADD COLUMN IF NOT EXISTS chosen_tier TEXT;

-- ====================================================================
-- SÄKERHETSINSTÄLLNINGAR (Row Level Security - RLS)
-- ====================================================================
ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.challenges DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_challenges DISABLE ROW LEVEL SECURITY;

-- ====================================================================
-- AUTOMATISK PROFILSKAPANDE (Trigger & Funktion)
-- ====================================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, alias)
  VALUES (
    new.id, 
    new.email,
    new.raw_user_meta_data->>'full_name', 
    new.raw_user_meta_data->>'alias'
  )
  ON CONFLICT (id) DO NOTHING; -- Säkrar om profilen redan skulle finnas
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Ta bort gammal trigger om den finns, för att undvika dubbletter innan vi skapar den på nytt
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Skapa tabellen för dagliga loggar
CREATE TABLE IF NOT EXISTS public.challenge_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  challenge_id BIGINT REFERENCES public.challenges(id) ON DELETE CASCADE NOT NULL,
  amount INT NOT NULL, -- Antal reps/squats gjorda
  logged_at DATE DEFAULT CURRENT_DATE NOT NULL, -- Sparar enbart datumet (ÅYYY-MM-DD)
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Stäng av RLS tillfälligt för detta test
ALTER TABLE public.challenge_logs DISABLE ROW LEVEL SECURITY;

-- 1. Ta först bort eventuella gamla dubbletter om du har testat mycket
-- (Detta rensar logg-tabellen så att spärren kan skapas utan fel)
TRUNCATE TABLE public.challenge_logs;

-- 2. Lägg till spärren som gör kombinationen av användare, challenge och datum unik
ALTER TABLE public.challenge_logs
ADD CONSTRAINT unique_user_challenge_date UNIQUE (user_id, challenge_id, logged_at);
