-- ====================================================================
-- FULLSTÄNDIGT DATABASSCHEMA FÖR UTMANINGSAPPEN (SÄKER VERSION)
-- ====================================================================

-- 1. TABELL: profiles (Användarprofiler kopplade till Supabase Auth)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email TEXT,
  full_name TEXT,
  alias TEXT UNIQUE,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS email TEXT;

UPDATE public.profiles AS profiles
SET email = users.email
FROM auth.users AS users
WHERE profiles.id = users.id
  AND profiles.email IS NULL;

-- Lägg till en admin-kolumn i profiles-tabellen
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS is_admin BOOLEAN DEFAULT FALSE;

-- 2. TABELL: challenges (Alla aktiva utmaningar skapade av Admin)
CREATE TABLE IF NOT EXISTS public.challenges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  points INT DEFAULT 100 NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Lägg till is_active i challenges-tabellen, förinställt på FALSE
ALTER TABLE public.challenges 
ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT FALSE;

-- Lägg till start- och slutdatum i challenges-tabellen
ALTER TABLE public.challenges 
ADD COLUMN IF NOT EXISTS start_date TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS end_date TIMESTAMPTZ;

-- 3. TABELL: user_challenges (Kopplingstabell: Vem har klarat vad?)
CREATE TABLE IF NOT EXISTS public.user_challenges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  challenge_id BIGINT REFERENCES public.challenges(id) ON DELETE CASCADE NOT NULL,
  completed_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Spärr så att en användare bara kan klara en specifik challenge en gång
  CONSTRAINT unique_user_challenge UNIQUE (user_id, challenge_id)
);

-- Lägg till valbara nivåer i utmaningstabellen
ALTER TABLE public.challenges 
ADD COLUMN IF NOT EXISTS tiers TEXT[] DEFAULT '{}';

-- Lägg till vilken nivå användaren har valt i kopplingstabellen
ALTER TABLE public.user_challenges 
ADD COLUMN IF NOT EXISTS chosen_tier TEXT;

-- ====================================================================
-- SÄKERHETSINSTÄLLNINGAR (Row Level Security - RLS)
-- ====================================================================
ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.challenges DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_challenges DISABLE ROW LEVEL SECURITY;

-- ====================================================================
-- AUTOMATISK PROFILSKAPANDE (Trigger & Funktion)
-- ====================================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, alias)
  VALUES (
    new.id, 
    new.email,
    new.raw_user_meta_data->>'full_name', 
    new.raw_user_meta_data->>'alias'
  )
  ON CONFLICT (id) DO UPDATE
  SET email = EXCLUDED.email; -- Håll e-postadressen synkroniserad med Auth
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- Ta bort gammal trigger om den finns, för att undvika dubbletter innan vi skapar den på nytt
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Skapa tabellen för dagliga loggar
CREATE TABLE IF NOT EXISTS public.challenge_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  challenge_id BIGINT REFERENCES public.challenges(id) ON DELETE CASCADE NOT NULL,
  amount INT NOT NULL, -- Antal reps/squats gjorda
  logged_at DATE DEFAULT CURRENT_DATE NOT NULL, -- Sparar enbart datumet (ÅYYY-MM-DD)
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Stäng av RLS tillfälligt för detta test
ALTER TABLE public.challenge_logs DISABLE ROW LEVEL SECURITY;

-- Lägg till spärren som gör kombinationen av användare, challenge och datum unik
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'unique_user_challenge_date'
      AND conrelid = 'public.challenge_logs'::regclass
  ) THEN
    ALTER TABLE public.challenge_logs
    ADD CONSTRAINT unique_user_challenge_date
    UNIQUE (user_id, challenge_id, logged_at);
  END IF;
END $$;

-- ====================================================================
-- ACHIEVEMENTS OCH AKTIVITETSRUM
-- ====================================================================
CREATE TABLE IF NOT EXISTS public.challenge_rooms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  challenge_id BIGINT REFERENCES public.challenges(id) ON DELETE CASCADE NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (id, challenge_id)
);

INSERT INTO public.challenge_rooms (challenge_id)
SELECT id FROM public.challenges
ON CONFLICT (challenge_id) DO NOTHING;

CREATE OR REPLACE FUNCTION public.create_challenge_room()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.challenge_rooms (challenge_id)
  VALUES (NEW.id)
  ON CONFLICT (challenge_id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

DROP TRIGGER IF EXISTS create_room_for_challenge ON public.challenges;
CREATE TRIGGER create_room_for_challenge
  AFTER INSERT ON public.challenges
  FOR EACH ROW EXECUTE FUNCTION public.create_challenge_room();

CREATE TABLE IF NOT EXISTS public.challenge_achievements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  challenge_id BIGINT REFERENCES public.challenges(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  condition_type TEXT NOT NULL CHECK (
    condition_type IN ('goal_percentage', 'daily_record')
  ),
  condition_value INT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT valid_achievement_condition CHECK (
    (condition_type = 'goal_percentage' AND condition_value BETWEEN 1 AND 1000)
    OR (condition_type = 'daily_record' AND condition_value IS NULL)
  )
);

CREATE TABLE IF NOT EXISTS public.user_achievements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  achievement_id BIGINT REFERENCES public.challenge_achievements(id) ON DELETE CASCADE NOT NULL,
  challenge_id BIGINT REFERENCES public.challenges(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  unlocked_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (achievement_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.challenge_room_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  challenge_id BIGINT REFERENCES public.challenges(id) ON DELETE CASCADE NOT NULL,
  room_id BIGINT NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  achievement_id BIGINT REFERENCES public.challenge_achievements(id) ON DELETE SET NULL,
  content TEXT NOT NULL CHECK (char_length(trim(content)) BETWEEN 1 AND 1000),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (achievement_id, user_id),
  UNIQUE (id, challenge_id),
  UNIQUE (id, challenge_id, room_id),
  CONSTRAINT challenge_room_messages_room_challenge_fkey
    FOREIGN KEY (room_id, challenge_id)
    REFERENCES public.challenge_rooms(id, challenge_id)
    ON DELETE CASCADE
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'challenge_room_messages_id_challenge_id_key'
      AND conrelid = 'public.challenge_room_messages'::regclass
  ) THEN
    ALTER TABLE public.challenge_room_messages
      ADD CONSTRAINT challenge_room_messages_id_challenge_id_key
      UNIQUE (id, challenge_id);
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.challenge_room_message_likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id BIGINT NOT NULL,
  challenge_id BIGINT NOT NULL,
  room_id BIGINT REFERENCES public.challenge_rooms(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_user_message_like UNIQUE (message_id, user_id),
  CONSTRAINT message_like_room_reference
    FOREIGN KEY (message_id, challenge_id, room_id)
    REFERENCES public.challenge_room_messages(id, challenge_id, room_id)
    ON DELETE CASCADE
);

ALTER TABLE public.challenge_achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.challenge_room_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.challenge_room_message_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.challenge_rooms ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.challenge_rooms TO authenticated;
GRANT SELECT, INSERT, DELETE
  ON public.challenge_room_message_likes TO authenticated;

DROP POLICY IF EXISTS "Participants can view challenge achievements"
  ON public.challenge_achievements;
CREATE POLICY "Participants can view challenge achievements"
  ON public.challenge_achievements FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.user_challenges
      WHERE user_challenges.challenge_id = challenge_achievements.challenge_id
        AND user_challenges.user_id = auth.uid()
    )
    OR EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.is_admin = TRUE
    )
  );

DROP POLICY IF EXISTS "Admins can manage challenge achievements"
  ON public.challenge_achievements;
CREATE POLICY "Admins can manage challenge achievements"
  ON public.challenge_achievements FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.is_admin = TRUE
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.is_admin = TRUE
    )
  );

DROP POLICY IF EXISTS "Users can view their achievements"
  ON public.user_achievements;
CREATE POLICY "Users can view their achievements"
  ON public.user_achievements FOR SELECT TO authenticated
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS "Participants can view room messages"
  ON public.challenge_room_messages;
CREATE POLICY "Participants can view room messages"
  ON public.challenge_room_messages FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.user_challenges
      WHERE user_challenges.challenge_id = challenge_room_messages.challenge_id
        AND user_challenges.user_id = auth.uid()
    )
    OR EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.is_admin = TRUE
    )
  );

DROP POLICY IF EXISTS "Participants can post room messages"
  ON public.challenge_room_messages;
CREATE POLICY "Participants can post room messages"
  ON public.challenge_room_messages FOR INSERT TO authenticated
  WITH CHECK (
    user_id = auth.uid()
    AND (
      EXISTS (
        SELECT 1 FROM public.user_challenges
        WHERE user_challenges.challenge_id = challenge_room_messages.challenge_id
          AND user_challenges.user_id = auth.uid()
      )
      OR EXISTS (
        SELECT 1 FROM public.profiles
        WHERE profiles.id = auth.uid() AND profiles.is_admin = TRUE
      )
    )
    AND (
      achievement_id IS NULL
      OR EXISTS (
        SELECT 1 FROM public.user_achievements
        WHERE user_achievements.achievement_id = challenge_room_messages.achievement_id
          AND user_achievements.challenge_id = challenge_room_messages.challenge_id
          AND user_achievements.user_id = auth.uid()
      )
    )
  );

DROP POLICY IF EXISTS "Participants can view their challenge rooms"
  ON public.challenge_rooms;
CREATE POLICY "Participants can view their challenge rooms"
  ON public.challenge_rooms FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.user_challenges
      WHERE user_challenges.challenge_id = challenge_rooms.challenge_id
        AND user_challenges.user_id = auth.uid()
    )
    OR EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.is_admin = TRUE
    )
  );

DROP POLICY IF EXISTS "Participants can view room message likes"
  ON public.challenge_room_message_likes;
CREATE POLICY "Participants can view room message likes"
  ON public.challenge_room_message_likes FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.user_challenges
      WHERE user_challenges.challenge_id = challenge_room_message_likes.challenge_id
        AND user_challenges.user_id = auth.uid()
    )
    OR EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.is_admin = TRUE
    )
  );

DROP POLICY IF EXISTS "Participants can like room messages"
  ON public.challenge_room_message_likes;
CREATE POLICY "Participants can like room messages"
  ON public.challenge_room_message_likes FOR INSERT TO authenticated
  WITH CHECK (
    user_id = auth.uid()
    AND (
      EXISTS (
        SELECT 1 FROM public.user_challenges
        WHERE user_challenges.challenge_id = challenge_room_message_likes.challenge_id
          AND user_challenges.user_id = auth.uid()
      )
      OR EXISTS (
        SELECT 1 FROM public.profiles
        WHERE profiles.id = auth.uid() AND profiles.is_admin = TRUE
      )
    )
  );

DROP POLICY IF EXISTS "Users can remove their room message likes"
  ON public.challenge_room_message_likes;
CREATE POLICY "Users can remove their room message likes"
  ON public.challenge_room_message_likes FOR DELETE TO authenticated
  USING (
    user_id = auth.uid()
    AND (
      EXISTS (
        SELECT 1 FROM public.user_challenges
        WHERE user_challenges.challenge_id = challenge_room_message_likes.challenge_id
          AND user_challenges.user_id = auth.uid()
      )
      OR EXISTS (
        SELECT 1 FROM public.profiles
        WHERE profiles.id = auth.uid() AND profiles.is_admin = TRUE
      )
    )
  );

CREATE OR REPLACE FUNCTION public.evaluate_challenge_achievements(
  p_user_id UUID,
  p_challenge_id BIGINT
)
RETURNS VOID AS $$
DECLARE
  selected_tier TEXT;
  target_amount NUMERIC;
  total_amount NUMERIC;
BEGIN
  SELECT chosen_tier INTO selected_tier
  FROM public.user_challenges
  WHERE user_id = p_user_id AND challenge_id = p_challenge_id;

  target_amount := NULLIF(
    substring(trim(COALESCE(selected_tier, '')) FROM '^[0-9]+'),
    ''
  )::NUMERIC;

  SELECT COALESCE(SUM(amount), 0) INTO total_amount
  FROM public.challenge_logs
  WHERE user_id = p_user_id AND challenge_id = p_challenge_id;

  INSERT INTO public.user_achievements (achievement_id, challenge_id, user_id)
  SELECT achievement.id, p_challenge_id, p_user_id
  FROM public.challenge_achievements AS achievement
  WHERE achievement.challenge_id = p_challenge_id
    AND (
      (
        achievement.condition_type = 'goal_percentage'
        AND target_amount > 0
        AND total_amount >= target_amount * achievement.condition_value / 100.0
      )
      OR (
        achievement.condition_type = 'daily_record'
        AND EXISTS (
          SELECT 1
          FROM public.challenge_logs AS current_log
          WHERE current_log.user_id = p_user_id
            AND current_log.challenge_id = p_challenge_id
            AND current_log.amount > COALESCE(
              (
                SELECT MAX(previous_log.amount)
                FROM public.challenge_logs AS previous_log
                WHERE previous_log.user_id = p_user_id
                  AND previous_log.challenge_id = p_challenge_id
                  AND previous_log.logged_at <> current_log.logged_at
              ),
              0
            )
        )
      )
    )
  ON CONFLICT (achievement_id, user_id) DO NOTHING;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

CREATE OR REPLACE FUNCTION public.refresh_challenge_achievements_for_logs()
RETURNS TRIGGER AS $$
BEGIN
  PERFORM public.evaluate_challenge_achievements(NEW.user_id, NEW.challenge_id);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

DROP TRIGGER IF EXISTS evaluate_achievements_after_log
  ON public.challenge_logs;
CREATE TRIGGER evaluate_achievements_after_log
  AFTER INSERT OR UPDATE ON public.challenge_logs
  FOR EACH ROW EXECUTE FUNCTION public.refresh_challenge_achievements_for_logs();

CREATE OR REPLACE FUNCTION public.refresh_challenge_achievements_for_tier()
RETURNS TRIGGER AS $$
BEGIN
  PERFORM public.evaluate_challenge_achievements(NEW.user_id, NEW.challenge_id);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

DROP TRIGGER IF EXISTS evaluate_achievements_after_tier
  ON public.user_challenges;
CREATE TRIGGER evaluate_achievements_after_tier
  AFTER INSERT OR UPDATE OF chosen_tier ON public.user_challenges
  FOR EACH ROW EXECUTE FUNCTION public.refresh_challenge_achievements_for_tier();

CREATE OR REPLACE FUNCTION public.refresh_challenge_achievements_for_definition()
RETURNS TRIGGER AS $$
DECLARE
  participant RECORD;
BEGIN
  FOR participant IN
    SELECT user_id
    FROM public.user_challenges
    WHERE challenge_id = NEW.challenge_id
  LOOP
    PERFORM public.evaluate_challenge_achievements(
      participant.user_id,
      NEW.challenge_id
    );
  END LOOP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

DROP TRIGGER IF EXISTS evaluate_achievements_after_definition
  ON public.challenge_achievements;
CREATE TRIGGER evaluate_achievements_after_definition
  AFTER INSERT OR UPDATE ON public.challenge_achievements
  FOR EACH ROW EXECUTE FUNCTION public.refresh_challenge_achievements_for_definition();

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime'
  ) AND NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'challenge_room_messages'
  ) THEN
    ALTER PUBLICATION supabase_realtime
      ADD TABLE public.challenge_room_messages;
  END IF;
  IF EXISTS (
    SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime'
  ) AND NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'user_achievements'
  ) THEN
    ALTER PUBLICATION supabase_realtime
      ADD TABLE public.user_achievements;
  END IF;
  IF EXISTS (
    SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime'
  ) AND NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'challenge_room_message_likes'
  ) THEN
    ALTER PUBLICATION supabase_realtime
      ADD TABLE public.challenge_room_message_likes;
  END IF;
END $$;
